server:
  port: 3333
  
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8080}/eureka/
      
zuul:
  prefix: /sbms
  routes:
    r1:
      path: /api1/**
      serviceId: WELCOME-SERVICE 
    r2:
      path: /api2/**
      serviceId: GREET-SERVICE
      
spring:
  application:
    name: API-GATEWAY